import { Tajawal } from "next/font/google";
import "../globals.css";
import {NextIntlClientProvider, useMessages} from 'next-intl';
import { Header, SideBar } from "../../components";
import PrelineScript from "@/components/PrelineScript";
import { useTranslations } from "next-intl";

import { unstable_setRequestLocale } from 'next-intl/server';

const primary = Tajawal({ subsets: ["latin"], weight: ["500", "700", "800"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Can be imported from a shared config
const locales = ['ar', 'fr'];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function RootLayout({ children, params: { locale } }) {
  unstable_setRequestLocale(locale);

  const t = useTranslations();
  const messages = useMessages();
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} >
     <NextIntlClientProvider messages={messages}>
          <body className={primary.className}>
        <>
          <Header />

          <SideBar locale={locale} />

          {/* <p className="text-4xl p-8 text-slate-800">{t("test")}</p> */}

          <div className="w-full pt-10 sm:px-6 md:px-8 lg:ps-72">
            <div className="p-4 mx-auto md:p-6 lg:p-8">
              {children}
            </div>
          </div>
        </>
      </body>
        </NextIntlClientProvider>
      
      <PrelineScript />
    </html>
  );
}
